### ISSUE TITLE
Minimum hardware test feature needed.

### ISSUE THREAD

**Issue by tfplenum** [tfplenum/rock#10]
<a href="https://github.com/Duckmanjbr"><img src="https://avatars3.githubusercontent.com/u/19156336?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Duckmanjbr](https://github.com/Duckmanjbr)**
_Sunday Dec 31, 2017 at 18:37 GMT_
_Originally opened as https://github.com/grantcurell/rock/issues/29_

----

Elasticsearch will not install w/ < 2GB RAM.  This hard code limit is fine we just need to add a function to test for minimum RAM first and display an error message if the box doesn't have enough.  We should also incorporate minimum CPU cores, drive space, etc.  This should be done early on in the install so new users don't spend time trying to trouble shoot after an install failure.

**Comment by GonzoVC** [comment]
@Duckmanjbr, I used the "assert" module to specify and check for minimum hardware requirements at the start of installation. If the check fails, the installation aborts and displays an error message. For now, I set the metrics to allow all TestVMs to succeed as long as they have 2-4GB+ of RAM and at least 2 CPU cores. I skipped the disk space checking as I'm still learning Ansible and trying to figure out a clean way to display that information while comparing it to a metric we specify. I doubt the code is efficient, but I'm starting to learn a lot as I see how everything is connected under the hood. Any help/tips would be greatly appreciated!

**Comment by Duckmanjbr** [comment]
Assert looks like the right way to go!  Is the plan per-playbook or having a master min-requiements playbook?  Maybe a bit of both?  We're only looking for minimum specs to get things installed and not error out without a message as to why.  You'll want to use variables so nothing is hard-coded for numbers.

**Comment by GonzoVC** [comment]
Right now, I have it as the first task that executes for anything listed with the "common" role so that it will check for requirements and abort prior to modifying the host settings. The checks themselves are super simple and probably not as dynamic as everyone would like.

Example:
```

# Verify minimum memory and CPU Core requirements for server install
- assert:
    that:
      - ansible_memtotal_mb >= {{ 2048 * 0.90 }}
    msg: "Not enough RAM (2GB+ required)! Aborting server install."
  when: serverlocal is defined and serverlocal

- assert:
    that:
      - ({{ ansible_processor_cores }} * {{ ansible_processor_count }}) >= 2
    msg: "Not enough CPU Cores (2+ required)! Aborting server install."
  when: serverlocal is defined and serverlocal

```
I went with this approach because it had the smallest footprint, only requiring a single line added into ../playbook/roles/common/tasks/main.yml and the corresponding playbook with the asserts listed out.

However, I do see the benefit of creating an entirely new role with a master playbook that can ensure enough resources are present on the localhost to support each service being installed.

I'm not sure how to modify this so that it becomes a "per-playbook" implementation. Would that just be simply adding these hardware checks within each ../roles/*/tasks/main.yml?
