### ISSUE TITLE
Kubernetes has a dependency on Docker

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#195]
Kubernetes has a dependency on Docker and right now we aren't enforcing that in any way. We are just ordering things correctly. This needs to be properly enforced somehow.

**Comment by dcode** [comment]
I recommend this in the kubernetes role.
```YAML
yum:
  name: docker
  state: present
```
