### ISSUE TITLE
Templates are broken in elasticsearch 6

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#30]
The following code in the elasticsearch main task no longer works in elasticsearch 6:

```
- name: "Load Bro Elasticsearch mapping templates"
  uri:
    body: "{{ lookup('file', 'es-bro-mappings.json')}}"
    body_format: json
    method: PUT
    url: "http://localhost:9200/_template/bro_index"
  when: "with_bro and bro_mapping.status == 404"
```

We need to re-evaluate the code for elasticsearch 6.
