### ISSUE TITLE
Ansible does not actually confirm service status

### ISSUE THREAD

**Issue by grantcurell** [tfplenum/rock#308]
Ansible does not guarantee that a service is running despite being in the started state. Use the following code to actually check a service:

```
- name: Check if dnsmasq is running
  command: systemctl status dnsmasq
  ignore_errors: yes
  changed_when: false
  register: service_dnsmasq_status

- name: Confirm dnsmasq is running
  fail:
    msg: "dnsmasq is not running for some reason. Log into {{ inventory_hostname }} and check status with 'systemctl status dnsmasq'"
  when: service_dnsmasq_status is failed
```

We need to make that a general function and use it whenever we are starting a service to ensure it actually begins running.
